### ISSUE TITLE
This dependency was not found

### ISSUE THREAD

**Issue by Arredatore** [Leesson/v-photoswipe#1]
Hi,

I'm looking for a good PhotoSwipe implementation for Vue now.  Your plugin after installation gives the "This dependency was not found" error.

**Comment by Arredatore** [comment]
After a small scrutiny - import { PhotoSwipe, PhotoSwipeGallery } from 'v-photoswipe/src' does work, but the default skin is broken

**Comment by Leesson** [comment]
Thanks for your feedback.  
This is a low-level mistake. I updated package's name but forgot npm main file. This is fixed and released as version 1.0.3 now.

**Comment by Arredatore** [comment]
Thank you
