### ISSUE TITLE
Icons not appearing. 

### ISSUE THREAD

**Issue by dmitrymalys** [Leesson/v-photoswipe#2]
Hi, I have set up the gallery with vue 2.5.2. Every thing works fine except icons, it do not show any icons, like arrows, close or share. It seems that SVGs is not loaded. Can you please tell me how I can able to fix it?

**Comment by Leesson** [comment]
@dmitrymalys You can copy the svg file `dist/default-skin.svg` to your dist directory for a temporary solution.
I will fix this bug and release it tomorrow.

**Comment by Leesson** [comment]
@dmitrymalys Just published `v1.0.3-1`.
Closing this issue, but feel free to continue discussion.
